import type { NiondraEntry } from './types';

// This file is no longer the primary source of data and will be removed in a future step.
// For now, it can be kept for reference or quick testing if needed.
export const initialEntries: NiondraEntry[] = [
  {
    id: '1',
    direction: 'given',
    person: 'Aunt Fatima',
    date: new Date('2023-05-20'),
    occasion: 'Wedding',
    giftType: 'Money',
    amount: 200,
    description: 'USD',
    notes: "For her daughter's wedding.",
  },
  {
    id: '2',
    direction: 'received',
    person: 'Uncle Ahmed',
    date: new Date('2023-08-15'),
    occasion: 'Birth',
    giftType: 'Sweets',
    amount: null,
    description: 'Large box of mixed mithai.',
    notes: 'For the birth of our son.',
  },
  {
    id: '3',
    direction: 'given',
    person: 'Cousin Zara',
    date: new Date('2024-01-10'),
    occasion: 'Housewarming',
    giftType: 'Item',
    amount: null,
    description: 'Decorative vase.',
  },
  {
    id: '4',
    direction: 'received',
    person: 'Grandma Sofia',
    date: new Date('2024-03-22'),
    occasion: 'Other',
    giftType: 'Money',
    amount: 100,
    description: 'CAD',
    notes: 'Eid gift.',
  },
    {
    id: '5',
    direction: 'received',
    person: 'Ali & Ayesha',
    date: new Date('2023-05-20'),
    occasion: 'Wedding',
    giftType: 'Item',
    amount: null,
    description: 'Dinner Set',
    notes: 'Our wedding gift.',
  },
];
